- hosts: target
  roles:
    - name: create thin pool
      role: thin-pool
    - name: create thin volume and mount
      role: thin-volume
      vars:
        data_size: "15G"
        data_name: docker_volume
        path_name: /var/lib/docker
